### ISSUE TITLE
Redirection to feed page

### ISSUE THREAD

**Issue by mhrechkin** [BinaryStudioAcademy/bsa-2023-writorium#114]
**User story:**
As a new user or an existing user who has logged out, I want to be directed to the feed page immediately after a successful log in or sign up, So that I can start browsing and interacting with the feed of articles without any additional steps.

**Acceptance criteria:**
- [x] After successful log in or sign up, the user should be automatically redirected to the feed page.
- [x] When a user clicks on the logo in the header, they should be redirected to the feed page.
- [ ] All available articles are displayed under the “Feed” tab in descending order (most recent first). - would be done after BE data fetch attached

**Comment by hnoievets** [comment]
If I understand the last criterion correctly, I can already remove the mocked articles and get them from the server. Right?

**Comment by andanf-e** [comment]
That's won't be a part of this task -- I believe @PablloZz is completing it with his task about articles page

**Comment by PablloZz** [comment]
Yeah, I'm almost done with it
