### ISSUE TITLE
Add ability to share articles

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#131]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/57cbf8b0-1ef9-476f-bc15-d359a1ffb742)

- [ ] Upon clicking on share button on article
    - make request to backend to generate token for getting shared article (token should contain `articleId` in payload)
    - form article sharing link (`<app_ulr>/article/shared/<token>` )
    - add formed link to clipboard
- [ ] Create public page for displaying shared article (upon `/article/shared/:token` route)
    - when user opens page article should be fetched by token (BE should decode token and return article by id from token payload)
    - shared article should not contain any action buttons

**Comment by Neyrinka** [comment]
Action buttons are displayed on shared article.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/28b504db-7b9c-45e3-bc0c-62e3fdefc544)

**Comment by kovAnya** [comment]
Action buttons already fixed
