### ISSUE TITLE
Show achievements on Profile

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#136]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/fa256f25-3a4e-4568-8078-8a96cb0bada4)

- [x] Create component to check user achievements
- [x] For now - just show few random achievements as user's achieved
- [x] Use modal to show whole list of achievements
- [x] As of now we'd not have proper design for it - so use simple view as from design mockup

**Comment by lera777** [comment]
- [x] The tooltip should be located within the modal window.


**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium
