### ISSUE TITLE
Show user activity section in Profile

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#137]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/75a47f5e-ca0f-45f8-967a-5187b312c834)

- [x] Create component showing user daily activity 
- [x] Make query for calculating how many articles user've been written/updated per day (for now by createdAt and updatedAt cols)
- [x] Use request that points on activity calculation on FE side to get activity data
- [x] Show up on created activity view - how many actions user've done per each day - (breakpoints for tiles: nothing: counted === 0, darken color: counted === 1, lighter: 1 < counted < 5, bright: counted >= 5), as of now use same coloring as on github activity bar

**Comment by andanf-e** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/b006aa82-f418-4871-ad22-9a68889b95fd)

Date cell on activity table does not actually corresponding to it's day's row
And add tooltips showing activity points

**Comment by lera777** [comment]
**Description**
In the Firefox and Safari browsers (macOS), the "Your writing activity" section is not displayed fully.



**Additional information:**


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/3a45ce0c-af20-449d-96cb-a7906ac239af)








**Environment:**
OS: macOS Catalina 10.15.7
Browser: Firefox, Safari

**Severity:**
Medium

**Priority:**
Medium

**Comment by lera777** [comment]
**Description:**
In the Firefox and Safari browsers (macOS), the "Your writing activity" section is not displayed fully.

**Actual result** (Firefox and Safari) :


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/533406fb-aee2-4a04-ae77-8a36b23cd8aa)

**Expected result**:


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/6e0a3419-d71c-4cc8-af7b-548deef0e31b)


Environment:
OS: macOS Catalina 10.15.7
Browser: Firefox, Safari

Severity:
Medium

Priority:
Medium
