### ISSUE TITLE
Apply status 4xx on Errors from authorization flow

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#140]
- [x] Update custom BE exceptions to be extended from HttpError exception
- [x] Path right 4xx status codes for that exceptions
- [x] Check if error notifications are shown on client side, when BE responses with error

**Comment by Neyrinka** [comment]
**Summary:**	The 500 error code is displayed in the console on the Sign Up page after entering the registered email in the email field.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	
1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Click the "Sign Up" button.
3. Enter the registered email in the "Email" field.
4.Enter the valid data in the "First name", "Last name", and "Password" fields.
5. Click the "Sign Up" button.
6. Pay attention to the error message and to the error code in the console.
7. 
**Actual Result:**	The 500 error code is displayed in the console on the Sign Up page after entering the registered email in the email field.

**Expected Result:**	The 403 error code and the error message "An account using this email already exists" is displayed on the Sign Up page after entering the registered email in the email field. (https://developers.rebrandly.com/docs/403-already-exists-errors)

**Attachments:**	

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/934904de-6b13-401b-b1bc-0e0f0a58964a)


**Severity:**	Low
**Priority:**	Medium

**Comment by Neyrinka** [comment]
**Summary:** The 500 error code is displayed in the console when trying to access secure pages with the invalid token.

**Environment:**
"OS: Windows 11
Browser: Google Chrome
Version: 116.0.5845.111"

**Expected Result:** The 401 error code is displayed when trying to access secure pages with the invalid token.

**Attachment:**
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/706a7527-c1a3-4be7-af97-07bc7dba7544)

**Severity:** Low
**Priority:** Medium

**Comment by hnoievets** [comment]
@Neyrinka, could you describe the steps to get this error?
