### ISSUE TITLE
Header Component

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#15]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/5f4053c5-36bf-4bb9-b0e0-a6efae7aee9a)

   **User story:**
   As an authorized user, I want to have a fixed header component placed at the top of the page, So that I can easily navigate to different sections of the application and access important information.

   **Acceptance criteria:**
- [x] The header component should consist of a logo and an avatar.
- [x] The header component should be placed on Layout for authorized users.
- [x] When a user scrolls through the content  the header component should remain fixed at the top of the page.
- [x] If a user clicks on the logo in the header from any page of the application, they should be redirected to the main page of the application.
- [x] If a user clicks on the avatar in the header, they should be redirected to profile page (in [Create dropdown with actions on header user avatar#108](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/issues/108)).

**Comment by Neyrinka** [comment]
**Summary:**	The header component is not fixed on the articles feed page when a user scrolls through the content

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	
1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Log in to the platform.
3. Go to the articles feed page.
4. Scroll the page down.
5. Pay attention to the header.

**Actual Result:**	The header component is not fixed on the articles feed page when a user scrolls through the content.

**Expected Result:** The header component is fixed on the articles feed page when a user scrolls through the content.

**Attachments:**	

https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/cab1af7f-119c-4e88-8815-f6b777393f1c



**Severity:**	Low
**Priority:**	Low


_**Note:** 1.3 in the Checklist_

**Comment by andanf-e** [comment]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/1c8af033-9668-4272-9454-10042b525644)
