### ISSUE TITLE
Add Article Preview upload on Create Article form

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#167]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/5b2d4a3e-fc6d-42ac-9def-3ed2eecaca53)

- [x] Remove mocked up Article Preview
- [x] Add Preview upload field to Create Article form
- [x] Apply flow with file upload similar to one that was done for avatar upload
- [x] Add preview_id (FK::files) col (previewId is optional so col should be nullable) to articles table (don't forget to make updates on db schema on readme)  
- [x] Update create article flow to also store previewId
- [x] Show saved preview on article if exists
**_Note._** _("preview_id" is replaced by "coverId")_

**Comment by Neyrinka** [comment]
Tested in Chrome, Edge (Windows). Works as expected.
