### ISSUE TITLE
Show user uploaded avatar in users header circle

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#172]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/bfe71494-8d54-4e42-b8d7-87b6cc45c0e9)

**Current behavior**
WHEN user uploads avatar and saves it - it is shown only in Profile

**Expected behavior**
WHEN user saves avatar - it should be linked also upon his user circle in header

**Comment by AnastasiaR2** [comment]
I noticed that when the articles page is opened for the first time and you click on read more, there is a redirect back to the articles page, and only then, clicking on read more redirects to the page with the chosen article. This happens every time the page is reloaded. I will fix it in this task as well.
