### ISSUE TITLE
Add Articles filtering functionality

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#184]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/1c924c08-464d-4edd-9347-8461750913d0)

- [ ] Add filters block on articles /feed and /my-articles pages
- [ ] Provide filtering functionality on
   - title - input that should pass filtering with debounce (to avoid BE calls on each input change)
   - author - would be shown only on articles /feed -- <- filtering options should be taken from `user_details` table (`label=first_name+last_name; value=user_id`)
   - genre <- filtering options should be taken from `genres` table (`label=name; value=id`)

Start implementing this branch functionality from branch with Infinite Scroll on `task/wr-138-articles-infinite-scroll`

**Comment by lera777** [comment]
- [ ] In the "My Articles" page the "Author" field should be hidden.
