### ISSUE TITLE
Implement add to favourites flow on articles

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#221]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/e7ace34d-3701-4d9c-b88c-a43cae726926)

- [ ] Create favoured_user_articles table (with article_id | user_id cols - _pair should be unique_)
- [ ] When current user fetches articles apply favoured mark (isFavoured) upon relation from favoured_user_articles table
- [ ] Add ability to mark\unmark article as favoured
- [ ] Add filtering option (toggle) to display favoured articles

**Comment by lera777** [comment]
**Descriotion:**
When reducing the browser window size, the circle goes beyond the toggle.




![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/45c52ad4-d8fd-42dd-abd3-f89344c08318)
