### ISSUE TITLE
Add ability to change article text font-size

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#234]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/359917fb-25b7-4a3a-93d6-63c8a2e3c164)
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/c5895738-7cfc-4c1f-abcc-42589a53125e)

- [ ] Create extension to provide an ability for changing text font-size
- [ ] Create action buttons to increase\decrease text font-size (may use svgs from mui-icons as on 2nd screenshot)
- [ ] Place font-size buttons at toolbar's start

**Comment by lera777** [comment]
- [ ] Place font-size buttons at toolbar's start, then "B", "I" icons and then icons for text alignment.


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/3dab5262-4264-4a0d-84eb-71d44d8a34e2)
