### ISSUE TITLE
Add a function to save article content in case the token expires

### ISSUE THREAD

**Issue by lera777** [BinaryStudioAcademy/bsa-2023-writorium#273]
**User Story:** 
  As a user, I want my article content to be preserved in the event of a token expiry, so that I can continue writing my article after re-authenticating.

**Acceptance Criteria:**
1. When a user is writing an article and their authentication token expires, the article content should be automatically saved in a temporary buffer.
2. When the user clicks the “Write” button after re-authentication, the previously entered article content should be pre-filled in the text editor, allowing the user to resume their writing from where they left off.
3. The user should not lose any unsaved changes to their article content during the token expiry and re-authentication process.

**Comment by andanf-e** [comment]
Save prompt text to `localStorage`
