### ISSUE TITLE
Prompt component for mobile/narrow screens

### ISSUE THREAD

**Issue by Neyrinka** [BinaryStudioAcademy/bsa-2023-writorium#281]
- [x] The "Show prompt" button should be placed after the slogan "Write your own story".
- [x] After clicking the "Show prompt" button should appear popover.
- [x] Popover should contain the prompt component with "Generate prompt" and "Reset prompt" buttons.

![Image](https://user-images.githubusercontent.com/48836066/269204104-9b3dd688-0629-438c-a926-b3b831b9fb86.png)

![Image](https://user-images.githubusercontent.com/48836066/269204242-21429113-89c7-4500-8bff-f81f02218b61.png)

**Comment by Neyrinka** [comment]
The button length should be the length of the "Show prompt" text.

**Comment by lera777** [comment]
- [x] All prompts should be the same length.


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/fb6067c2-0c0f-4ab8-8c8e-56a3044fd42f)
