### ISSUE TITLE
Prompt generation component

### ISSUE THREAD

**Issue by mhrechkin** [BinaryStudioAcademy/bsa-2023-writorium#29]
- [x] Implement frontend part of the prompt generation component
- [x] When pressing shuffle button, animation should work like [here](https://diymfa.com/writer-igniter/)(data should be hardcoded)

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/83463107/a51dd76d-4932-47c3-a09b-51b44fbe5616)

**User story:**
As a writer, I want to generate diverse prompts for various topics, so that I can enhance my creative output.

**Acceptance criteria:**

- [ ] The prompt generation block should be placed on the top of the create article page.
- [ ] The title "Write your own story" should be placed on the top of the prompt generation block.
- [ ] The prompt generation block should consist of character, situation, setting, prop, genre fields, and a shuffle button placed below the block title.
- [ ] When the user clicks the shuffle button the system should generate a completely random prompt from a diverse range of topics and the generated random prompt is shown to the user.

**Comment by Neyrinka** [comment]
**Summary:**	The prompt fields do not indicate the loading process on the prompt component after clicking the shuffle button.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	
1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Log in to the platform.
3. Click the "Write" button on the header.
4. Click the shuffle button on the prompt component.
5. Pay attention to the prompt fields.

**Actual Result:**	The prompt fields do not indicate the loading process on the prompt component after clicking the shuffle button.

**Expected Result:**	The three **dot-flashing** are displayed on the prompt fields of the prompt component after clicking the shuffle button. (https://codepen.io/nzbin/pen/GGrXbp?editors=1100)

**Attachments:**	

https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/2da2cf31-d8d4-479d-983d-0e2a48980e46



**Severity:**	Low
**Priority:**	Low


_**Note:** 6.3 in Checklist_

**Comment by andanf-e** [comment]
Fact that it's not scrolling is expected, but I believe we need to add some loading animation on prompt fields, when it's being generated

**Comment by Neyrinka** [comment]
So the second item doesn't mean it? "When pressing shuffle button, animation should work like [here](https://diymfa.com/writer-igniter/)(data should be hardcoded)"

**Comment by andanf-e** [comment]
That part was related for hardcoded data for prompts, currently we are not using hardcoded prompts
