### ISSUE TITLE
Rework latest articles section to look like on the design

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#291]
<img width="384" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/d53c002f-12c0-4d66-8e2e-8a85c5c3e903">

- [x] Do not include `Read more` button -> make a link on article's title
- [x] Add show all link below articles

**Comment by drMangust** [comment]
> Add show all link below articles

Should I write an action for the link right away? Will this be a link to the feed with query filter parameters by author?

**Comment by andanf-e** [comment]
> > Add show all link below articles
> 
> Should I write an action for the link right away? Will this be a link to the feed with query filter parameters by author?

Just leave show articles - as it is now on profile, pointing to `/my-articles`
