### ISSUE TITLE
Add like/dislike buttons on the fixed panel

### ISSUE THREAD

**Issue by lera777** [BinaryStudioAcademy/bsa-2023-writorium#300]
- [x] The like/dislike action buttons on the Article view page should be positioned on the right side of the article’s footer within a fixed panel.

https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/44fc5dac-2259-4cf0-afbb-81a3ee1623b8

- [x] This panel should remain stationary and not scroll along with the page as a user scrolls through the article content.

- [x] For mobile/narrow screens, the like/dislike buttons should be positioned beneath the article text.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/d201e2f8-ffd2-43b5-b9e1-ba89ea210ac3)

- [x] Like/dislike icons, view icon and comments icon should not be displayed for draft articles.

**Comment by AnastasiaR2** [comment]
As I understand, I should remove like/dislike icons, view icon and comments icon both from my articles and article view page on draft. Should I also remove the share buttons?
