### ISSUE TITLE
Implement article saving logic | BE

### ISSUE THREAD

**Issue by mhrechkin** [BinaryStudioAcademy/bsa-2023-writorium#31]
**User story:**
As a writer, I want to have control over publishing and drafting articles, so that I can decide whether an article should be published immediately or saved as a draft, and it appears correctly in the “My Articles” tab and feed.

**Acceptance criteria:**
- [x] After clicking the “Publish” button, the article should be listed in the “My Articles” tab on the “My articles” page. The article should also appear in the feed for all users to see.
- [x] The articles table migration  for creating table should include the “published_at” column, for indicating the publication date of articles on the feed.
- [x] After clicking the “Save Draft” button, the article should be listed in the “My Articles” tab  on the “My articles” page with a “draft” label.

![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/4137e322-6625-45a4-b6c8-311ba1a43052)

**Comment by drMangust** [comment]
Do I understand correctly that published_at will be used to display only those that have been published. That is, if published_at === null (null by default), then this publication will be available only to the person who created it (made a save draft).

At the moment, my task is to make only a save draft or should there be more logic?

**Comment by mhrechkin** [comment]
Yes, you are right, if published_at is null, it means it is a draft. For now, you just need to add the save logic.
