### ISSUE TITLE
Move prompt generation section to the right side

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#320]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/4a0c27b4-42a6-498c-97fb-4404145fa496)

**Comment by lera777** [comment]
- [x] The prompts should be aligned with the text.



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/ea24c621-42ba-49f3-bfc7-90367fd915a5)
