### ISSUE TITLE
Add prompt usage confirmation

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#322]
<img width="511" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/44ea398d-00f8-410d-bc00-04d7c982fdda">

- [ ] On article creation WHEN prompt was generation for article - add Modal to confirm what prompt category was used for written article
- [ ] By default prompt categories should be toggled on
- [ ] WHEN prompt category is toggled off - do not pass it on article submit

**Comment by Neyrinka** [comment]
- [x] Add text to the confirmation dialog "Please, select the prompts that you have used."
- [x] Place the prompt text under the prompt title for mobile screens.
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/008b80d3-a88c-42d2-ae7c-3b5dd7679582)

- [x] Align the text in the Confirm prompts button
- [x] Reduce the side indentation for mobile screens

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/fdcd8646-3cf4-4d8f-8f3c-65ae752384ee)
