### ISSUE TITLE
Fix the displaying articles on the site pages for mobile/narrow screens

### ISSUE THREAD

**Issue by Neyrinka** [BinaryStudioAcademy/bsa-2023-writorium#328]
On the Feed/My articles page for mobile/narrow screens:

- [ ] The genre of the article should be fully displayed
- [ ] The text about the approximate time of reading the article should be displayed in one line
- [ ] Read more link should be displayed in one line.
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/6461edd4-3634-4c8b-9113-a87b2be14e4c)

- [ ] The width of the prompt fields should be equal for all fields on the Feed page.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/f721292a-184f-4e89-830c-8fd57684875b)

- [ ] Align text in the "Save draft" button on the Write page

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/d532ec74-84ea-496d-b171-06bb6c457e85)

- [ ] Shift the text from the X icon in the delete confirmation dialog

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/5a3e4d8d-76bd-4df8-8451-8bf8ace7a28b)

**Comment by lera777** [comment]
**Description:**

On iPhone 12 mini, the filter icon is not displayed


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/53f7d0e0-ac0c-4ce6-bde2-7b27ed4051e9)


Ellipses(...) in prompts are not displayed if the text is not fully visible.


![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/b384ea80-f85a-4561-b399-e48bd7acf62c)

Horizontal scroll is displayed.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/c955d370-a2ff-47ed-b848-c21948f719dd)

The close (X) icon in the confirm dialog for deleting the article is adjacent to the text.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/851df2d5-8ff6-4327-92a7-6d1215d3cd1e)
