### ISSUE TITLE
Add more proper achievement description tooltip regarding to progress

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#388]
<img width="880" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/b3a7515c-de54-4dee-91e4-84de5b8ebed8">

- [x] Add progress breakpoints for tooltip text mapping (same as for coloring progress line on tooltip)

**Comment by Neyrinka** [comment]
The tooltip for an article is displayed for the comment achievement.

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/4c80708e-f51a-47b8-aadb-79c9bd7da8e0)
