### ISSUE TITLE
Fix loader inside share popover

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#405]
<img width="262" alt="image" src="https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/eb54403a-d03a-4dea-aab3-a10f0e79a420">

Loader should not cover whole popover, maybe would be suitable to replace it with dots loader (and only for facebook sharing button)

**Comment by drMangust** [comment]
@andanf-e 
The problem is not in copying to the buffer, but in sharing to Facebook. Before you click on the Facebook button, you need to have a link for sharing, so this option was chosen.

**Comment by andanf-e** [comment]
> @andanf-e The problem is not in copying to the buffer, but in sharing to Facebook. Before you click on the Facebook button, you need to have a link for sharing, so this option was chosen.

Thanks!
