### ISSUE TITLE
Implement article card component

### ISSUE THREAD

**Issue by mhrechkin** [BinaryStudioAcademy/bsa-2023-writorium#51]
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/83463107/b7a5efd6-add3-4bfe-872a-e601cdf22cb9)

**User story:**
As a content consumer, I want to see visually appealing and concise previews of articles, each containing key information and an image, so that I can quickly browse and select articles of interest.

**Acceptance criteria:**

- [x] Articles on the article feed should be displayed by a separate article component.
- [x] Each article card component should contain the author, publication date, time to read the article, title, image, genre, icons with the specified number of comments, views, likes, dislikes, "Share", "Save" icons, and "Read more" link.
- [x] Each element on the article card component should be placed as in design, including size, colors, fonts.
- [ ] Clicking on the "Like" icon should add a like if the user hasn't already liked the article, and remove the like if the user has previously added it.
- [ ] Clicking on the "Dislike" icon should add a dislike if the user hasn't already disliked the article, and remove the dislike if the user has previously added it.
- [ ] Clicking on the "Comment" icon, a user should be directed to the full page with the article, and scroll to the block with comments.
- [ ] Clicking on the “Save” icon should trigger the article to be saved to the user’s “My Articles” tab.
- [ ] Clicking on the "Read more" link, a user should be directed to the full article page for that specific article.
- [ ] Clicking on the “Share” icon should open a submenu with icons for sharing the article on Facebook and Twitter.
- [ ] Clicking on the “Twitter” icon should open a new window with a pre-populated tweet containing the article’s title and a link to the article.
- [ ] Clicking on the “Facebook” icon should open a new window with a pre-populated Facebook post containing the article’s title and a link to the article.

**Comment by lera777** [comment]
**Description**

- [x] Text is not properly spaced from the adjacent element and is directly attached to the hints block. 
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/9cefac26-50f3-4b53-b128-2f4abc78599d)

- [x] The cursor pointer appears when hovering over the icon displaying the view count. 
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/7f15acf9-1d59-4ad0-b638-9cb5f9ef7fc6)

- [x] When the text in an article lacks spaces, it extends beyond the boundaries of the article card.
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/0d0a32c7-c17a-4f89-aafa-fc56a021b872)


**Expected result:**
1 A visible margin or padding to separate the text from the hints block.
2 It should remain a regular cursor, as there is no interactive functionality associated with it.
3 The text stay within the card limits.


**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Medium

**Priority:**
Medium
