### ISSUE TITLE
Sign In | FE

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#6]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/1480d386-1525-49b7-9bdd-f73a7de17bc2)
[template - put only needed things from design]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/13a3c1bf-1a25-41a2-a488-e2be718c34ec)

  **User story**:
 As a registered user, I want to be able to sign in to my account using my credentials, So that I can access personalized features and data within the application.

  **Acceptance criteria:**
- [x] The sign-in form should include mandatory fields for entering email and password, “Sign In” button, “Sign Up” button.
- [x] The Email field should consist of a local and a domain part separated by a symbol @ and accept lowercase latin letters, uppercase latin letters, digits, special characters, dot.
- [x] When a user enters an invalid email address he should get an error message “Please, enter a correct email”.
- [x] The Password field should be at 4-20 characters long. When a user enters an invalid password he should get an error message “Your password must be at 4-20 characters long.”
- [x] If a user leaves an email or password field empty, this field should be highlighted in red and the “This field is required” error message should be displayed next to this field, indicating that they are mandatory.
- [x] Validation _shared with BE_
- [x] When a user clicks the “Sign In” button, the service should perform validation that the password and email mandatory fields are filled in and data should be sent to the back-end for validation and authentication.
- [ ] If authentication is successful, the user should be redirected to the application’s main page.
- [ ] If authentication fails, the “Login failed. Invalid Email or Password” error message should be displayed indicating failure.
- [x] Clicking the “Sign Up” button successfully redirects to the sign-up page.

**Comment by Neyrinka** [comment]
**Summary:**	The entered text and background are displayed in different colors in the "Password" and "Email" fields on the Sign In form when a user fills the fields.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	

1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Pay attention to the "Email" and "Password" fields.

**Actual Result:**	The entered text and background are displayed in the same color in the "Password" and "Email" fields on the Sign In form when a user fills the fields.

**Expected Result:**	The entered text and background are displayed in different colors in the "Password" and "Email" fields on the Sign In form when a user fills the fields.

**Attachments:**	
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/28f8a481-f31f-4ed1-9df6-a13f490c1b7c)


**Severity:**	Low

**Priority:**	Medium
