### ISSUE TITLE
Edit User Profile functionality

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#60]
**FE**
**User story:**
 As a registered user of the platform, I want to be able to edit my profile, so that I can keep my profile information up to date.

**Acceptance criteria:**

- [x] Clicking the “Edit profile” button switches the non-editable details to an editable Edit user form.
- [x] The editable form contains input fields for first name, last name, email and profile picture.
- [x] The input fields in the edit form are prepopulated with accurate existing user information.
- [x] The user can modify any or all fields within the edit form.
- [x] The Email field should accept email consisting of a local and a domain part separated by a symbol @ and accept lowercase latin letters, uppercase latin letters, digits, special characters, dot.
- [x] When a user enters an invalid email address this field should be highlighted in red and the “Please, enter a correct email” error message is displayed.
- [x] The First name/Last name field should accept lowercase latin letters, uppercase latin letters.
- [x] When a user enters an invalid First name/Last name this field should be highlighted in red and the “Please, enter a correct First name/Last name” error message is displayed.
- [x] A “Cancel” button is provided to revert changes and return to non-editable mode.
- [x] A “Save” button is available to save the edited information.
- [x] Clicking the “Save” button triggers validation to ensure proper data is entered.
- [x] After successful validation, the user details section switches back to non-editable mode, displaying updated information.
- [x] Skip changing avatar for now
- [x] On form submit PUT request should be fired
**BE**
- [x] Provide route to handle PUT request for `/users`
- [x] Provide validation (shared BE/FE)
- [x] Provide repository/service method to update User data

**Comment by lera777** [comment]
**Description**
The "Cancel" button and the disabled "Save" button do not match the design.

**Steps to reproduce:**

1 Open website on the profile page https://writorium-development-1c771c6e3c1a.herokuapp.com/profile.
2 Click the "Edit profile" button.
3 Hover cursor over the "Save" button.
4 Pay attention on the "Cancel" button and the disabled "Save" button does not match the design.

**Actual result:**
The "Cancel" button and the disabled "Save" button do not match the design.

**Expected result:**
The "Cancel" button matches the design and the disabled "Save" button is light green.

**Additional information:**



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/129b519e-9beb-493a-a8c1-72204dbd5d82)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/042bbb19-1147-40f3-8853-71d89072d64c)


**Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium
