### ISSUE TITLE
Add Articles page

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#75]
![image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19575839/2715d9b6-d916-4433-a652-457da113e4c5)
**User story:**
As a logged user, I want to be able to explore and engage with articles, so that I can easily create new articles and stay informed about the latest content from other authors and share my own insights with the community.

**Acceptance criteria:**
- [x] Add page upon `/articles` route
- [x] Page should have 2 tabs: `Feed` and `My articles` (for now - may show both mocked Article cards
- [x] Page should be protected
After save article task would be merged - rely on data from BE + link it with articles fetch
- [x] Two tabs labeled “Feed” and “My Articles” should be visible on the Articles page.
- [x] The “Feed” tab should be the active tab by default.
- [x] User should be able to switch between tabs without any issues.
- [x] If an unauthorized user attempts to navigate to the Articles page he should be redirected to the login page.
- [x] The “Feed” tab should display all available articles, including the ones created by the user.
- [x] All available articles are displayed under the “Feed” tab in descending order (most recent first).
- [x] Articles created by the user are shown under the “My Articles” tab in descending order (most recent first).

**Comment by lera777** [comment]
- [ ] Horizontal scroll should not be displayed on the page.

**Additional information:**
![Screenshot at Sep 11 17-34-14](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/c28b7c73-515a-437f-bda1-4a622ba671a1)

 **Environment:**
OS: macOS Catalina 10.15.7
Browser: Google Chrome 116.0.5845.110

**Severity:**
Low

**Priority:**
Medium
