### ISSUE TITLE
Implement articles reactions flow

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#77]
- [x] Create migration to add `article_reactions` table
- [x] Create repository/service/controller for reactions (getting reactions by article_id, saving reaction per article)
Should start this branch from base with articles saving

**Comment by hnoievets** [comment]
Need I implement an updating reaction?

**Comment by andanf-e** [comment]
Yep, 
Reaction **update** would be triggered by toggling `like`/`dislike` (WHEN user already `liked` article, but then clicks on `dislike` then we're **updating** reaction record _isLike_ field),,
Also when user detaches reaction (WHEN user already `liked` article and then clicks on `like` - then **delete** reaction record)

**Comment by hnoievets** [comment]
Got it, thanks

**Comment by hnoievets** [comment]
Then ArticlereactionUpdateRequestDto will only consist of isLike?

**Comment by hnoievets** [comment]
When we delete a reaction on update, what should we return?
