### ISSUE TITLE
Implement Forget Password flow

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#80]
- [ ] Add forget password link above Password field on Sign-In page
- [ ] Add form with `email` for forget password on public page
- [ ] Add `/send-forget-password` auth route
- [ ] Add password changing form (2 fields Password + Confirm Password) on public page -> should be opened from email link
- [ ] Apply password+confirm_password fields check
- [ ] Add email service (use https://nodemailer.com/ as email engine and https://sendgrid.com/ as email API (will share creds for SendGrid via DM)) -> add sendChangePasswordEmail method
- [ ] Add /reset-password auth route
Flow:

1. User clicks `forget password` link -> redirect to `forget password` page with email field and send button
2. When user requests changing password -> request being send BE - BE checks if user exists, if so
    - generates change password token (with `userId` in payload) - that expires in `1h`
    - sends email for user with reset-password link (`/reset-password/{generated_token}`)
3. When user gets email with reset password link -> upon clicking on link - user is redirected on reset password page `/reset-password/{generated_token}` -- page contains password+confirm_password fields and submit button
4. When user submits new password (payload: `password: string; confirmPassword: string; resetPasswordToken: string`) -> BE validates passwords same way as frontend + decodes `resetPasswordToken` if token is valid then password is updated with new one and user gets authorized

**User story:**
As a user who has forgotten the password, I want a simple and secure process to reset my password, so that I be able to regain access to my account.

**Acceptance criteria:**

- [ ] A forget password link should be placed below the Password field on the Sign-In page.
- [ ] Clicking the forget password link should direct a user to the forget password page.
- [ ] The forget password page should contain the Email field and the "Send" button.
- [ ] When a user submits the form the system should validate the email address to ensure it exists in the user database.
- [ ] If a user is registered, the system should generate a change password token that expires in 1h and send an email to the user with a reset password link.
- [ ] If a user is not registered, the error message "User with this email not found" should appear.
- [ ] Clicking the provided password reset link should direct a user to the reset password page.
- [ ] The reset password page should contain a password, confirm password fields, and the "Submit" button.
- [ ] The "Submit" button should be active after all fields are filled in.
- [ ] The Password field should accept lowercase latin letters, uppercase latin letters, digits, and special characters. Minimum length - 4, maximum length - 20.
- [ ] The password must contain at least one special character and at least one uppercase latin letter.
- [ ] When a user enters an invalid password he should get an error message “Password must contain at least one special character and one uppercase latin letter”.
- [ ] When a user enters more than 21 symbols the error message should appear "The maximal password length - 20".
- [ ] When a user enters less than 4 symbols the error message should appear “The minimal password length - 4".
- [ ] If the entered data in the password and confirm password fields are different, the error message "Passwords do not match" should appear.
- [ ] After successful validation user should be authorized and directed to the articles page.

**Comment by Neyrinka** [comment]
**Summary:**	The internal server error is displayed on the Forgot password page after clicking the "Send" button with entering the registered email.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	
1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Click the "Forgot password?" button.
3. Enter the registered email.
4. Click the "Send" button.
5. Pay attention to the error message.

**Actual Result:**	
The internal server error is displayed on the Forgot password page after clicking the "Send" button with entering the registered email.

**Expected Result:**	 
The reset password link is sent to the user's email on the Forgot password page after clicking the "Send" button with entering the registered email.

**Attachments:**	

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/c6fa5027-7f23-417b-81e0-9955a5480626)



![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/4c9e5359-97d6-4bf4-99b6-943f1369da9a)




**Severity:**	Critical
**Priority:**	High

**Comment by Neyrinka** [comment]
**Summary:**	The Hide/Show Password Eye icon is not displayed on the password changing form. 

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Steps to reproduce:**	
1. Go to https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2. Click the "Forgot password?" button.
3. Enter the registered email.
4. Click the "Send" button.
5. Open the link in the email.
6. Pay attention to the password fields.

**Actual Result:**	The Hide/Show Password Eye icon is not displayed on the password changing form. 
**Expected Result:** The Hide/Show Password Eye icon is  displayed on the password changing form. 

**Attachments:**	

![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/2b2ca2b1-b9ae-4581-8c88-3b614ec17763)



**Severity:**	Medium
**Priority:**	Medium
