### ISSUE TITLE
Authorization Token

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#9]
**User story:**
As a user, I want to stay logged in when I revisit the app later so that I don’t have to enter my credentials every time.

**Acceptance Criteria:**
- [x] If a user successfully signed up and his account is created then a unique  JWT Verification token should be generated.
- [x] If the user sign in and the user’s account credentials are verified, then a unique  JWT Authorization token should be [Implement](https://www.npmjs.com/package/jose) for the user’s session.
- [x] The token should be passed to the frontend and stored in the  local Storage.
- [x] The JWT token should store the user’s id.
- [x] The token should have an expiration time - one day. The token should become invalid and unusable after the expiration time.

**Comment by lera777** [comment]
**Description**
After the token expires, there is no redirect to the sign-in page.

**Steps to reproduce:**

1 Open website https://writorium-development-1c771c6e3c1a.herokuapp.com/sign-in.
2 Log in to your account.
3 After 24 hours have passed, please attempt to edit your profile.
4 Pay attention to the fact that after the token expires, there is no redirect to the sign-in page.

**Actual result:**
After the token expires, there is no redirect to the sign-in page.

**Expected result:**
After the token expires, there is a redirect to the sign-in page.

**Additional information:**




https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/19595678/4d18bb26-796b-42f5-b8ca-43a6a2d50f74





**Environment:**
OS: macOS Catalina 10.15.7
Browser: Firefox 117.0

**Severity:**
High

**Priority:**
Medium

**Comment by Neyrinka** [comment]
- [ ] The error message should be human-readable when the token expires.
