### ISSUE TITLE
Create inner prompt for OpenAI call to specify created article genre

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#90]
When article is submitted:
- [x] Take article text and pass it to OpenAI prompt to get genre of that story (may return an array of genres)
- [x] As of initial implementation just save one of returned genres (if present) as article's genre
- [x] If our app's `genres` does not contain genre that is applied for article, then save it in `genres`

**Comment by Neyrinka** [comment]
**Actual Result:** The genre is not displayed when the AI cannot determine the genre of the article

**Expected Result:** The genre should be set as "unknown" when the AI cannot determine the genre of the article.
