### ISSUE TITLE
Implement avatar upload upon Profile editing

### ISSUE THREAD

**Issue by andanf-e** [BinaryStudioAcademy/bsa-2023-writorium#95]
- [x] Add `avatar_id` column to `user_details`
- [x] Create files relation for avatar on user_details
- [x] Add avatar file (avatarUrl) linking to user entity
- [x] On Edit profile wrap avatar with input (`type='file'`)
    - with onChange event firing file upload action (will upload file) and return file entity
- [x] Upon successfull file upload - pass file id to avatarId for edit profile payload
Create branch based on Edit User Profile functionality

**User story:**
 As a registered user of the application, I want to be able to upload a new avatar for my profile and easily remove it when needed,
So that I can personalize my profile and have control over my avatar.

**Acceptance criteria:**
- [x]  When the user hovers the cursor over the avatar in the profile editing page, a lighter background should highlight the avatar and an edit icon should appear, indicating that the avatar is editable.
- [x]  Upon clicking the edit icon, a file picker dialog opens.
- [x]  The user can select an image file from their device.
- [x]  The Avatar field accept png/jpeg pictures with size less than 10Mb.
- [x] “The selected file exceeds the maximum allowed size of 10 Mb.” error message is displayed when a user attempts to upload an avatar file larger than the allowed size.
- [x]  After selecting an image, a preview of the chosen image is displayed on the page.
- [ ]  The user can reposition and crop the image if needed before proceeding. (**_skip for now_**)
- [x]  After successfully uploading a new avatar  the profile should reflect the changes.
- [x]  If there is no avatar uploaded, there should be no remove button displayed.
- [x]  When the user hovers the cursor over their avatar icon a small cross (“X”) icon should be displayed in the right upper corner of the avatar icon.
- [ ]  When the user clicks on the cross (“X”) icon after hovering a confirmation dialog should appear. (**_skip for now_**)
- [ ]  When the user clicks the “Cancel” button the dialog should close, and the avatar should remain unchanged. (**_skip for now_**)
- [ ]  When the user clicks the “Remove” button the avatar should be removed from the user’s profile. (**_skip for now_**)

**Comment by Neyrinka** [comment]
**Summary:** The error message doesn't contain information about the maximum file size in the Profile editing after selecting the image with a size greater than 10 Mb.

**Environment:**	
"OS: Windows 11
Browser: Google Chrome 
Version: 116.0.5845.111"

**Expected Result:** “The selected file exceeds the maximum allowed size of 10 Mb” error message is displayed when a user attempts to upload an avatar file larger than the allowed size.

**Attachments:**	
![Image](https://github.com/BinaryStudioAcademy/bsa-2023-writorium/assets/48836066/971e6736-9b53-48e0-87e4-584414a8fff4)


**Severity:**	Low
**Priority:**	Low
